### ISSUE TITLE
issue with Cityscapes Instance segmentation evaluation

### ISSUE THREAD

**Issue by abhishekaich27** [hujiecpp/YOSO#19]
Hi @hujiecpp,

The following error occurs when I evaluate YOSO for instance segmentation on Cityscapes dataset using your provided model. Can you verify this evaluation on your end?

<img width="906" alt="MicrosoftTeams-image" src="https://github.com/hujiecpp/YOSO/assets/30926705/4bd17370-64ae-4cd7-88fa-3a2593caa1b4">

I was able to replicate the panoptic and semantic results. Thank you for your great work!

**Comment by hujiecpp** [comment]
Hi @abhishekaich27 , 
Sorry for the late reply, this issue can be solved by uncommenting the [code](https://github.com/hujiecpp/YOSO/blob/04b898d395ffd8318aa3761b0b2b6d20b3514f26/projects/YOSO/yoso/segmentator.py#L242) and setting both INSTANCE_ON and PANOPTIC_ON in the [config ](https://github.com/hujiecpp/YOSO/blob/04b898d395ffd8318aa3761b0b2b6d20b3514f26/projects/YOSO/configs/cityscapes/panoptic-segmentation/YOSO-R50.yaml#L35)to True.

**Comment by abhishekaich27** [comment]
Great, will try. Curious that why it works for COCO with only `INSTANCE_ON=True` but needs an additional `PANOPTIC_ON=True` for Cityscapes. Any comments? (I may have missed out some detail specific to Cityscapes)

**Comment by abhishekaich27** [comment]
This worked. Closing issue.
