### ISSUE TITLE
About the results on ADE20k

### ISSUE THREAD

**Issue by zhoujh2020** [hujiecpp/YOSO#2]
Hello, I evaluated the results of your YOSO on ADE20K according to the method you provided, but we got the following data:
![image](https://user-images.githubusercontent.com/71644268/229396782-be30bae5-2fac-45be-b0d2-d42f5cfc3f92.png)
This result is much weaker than the result in your article. May I ask whether it is a model upload error or a problem with my details. Thank you for your help.

**Comment by hujiecpp** [comment]
Thanks for pointing out this issue. We found that lower OBJECT_MASK_THRESHOLD can bring better PQ results on ADE20K, please change "OBJECT_MASK_THRESHOLD: 0.8" to "OBJECT_MASK_THRESHOLD: 0.2" in the [config file](https://github.com/hujiecpp/YOSO/blob/main/projects/YOSO/configs/ade20k/panoptic-segmentation/YOSO-R50.yaml). We have also modified this file in the repo.

**Comment by zhoujh2020** [comment]
Thank you very much for your kind and prompt reply.

**Comment by zhoujh2020** [comment]
Thank you very much for your kind and prompt reply. I want to ask another question, what method do you use to calculate fps (manual calculation or calling some library).

**Comment by hujiecpp** [comment]
The FPS is calculated from "Total inference pure compute time" reported in the detectron2 evaluator.

For example, the FPS with four 3090 GPUs on ADE20K is calculated via $1/0.025790\approx38.77$.

> ......
> [04/03 10:26:21] d2.data.common INFO: Serialized dataset takes 1.95 MiB
> [04/03 10:26:21] d2.evaluation.evaluator INFO: Start inference on 500 images
> [04/03 10:26:28] d2.evaluation.evaluator INFO: Inference done 11/500. 0.0266 s / img. ETA=0:00:19
> [04/03 10:26:34] d2.evaluation.evaluator INFO: Inference done 130/500. 0.0263 s / img. ETA=0:00:15
> [04/03 10:26:39] d2.evaluation.evaluator INFO: Inference done 241/500. 0.0273 s / img. ETA=0:00:11
> [04/03 10:26:44] d2.evaluation.evaluator INFO: Inference done 360/500. 0.0266 s / img. ETA=0:00:06
> [04/03 10:26:49] d2.evaluation.evaluator INFO: Inference done 491/500. 0.0259 s / img. ETA=0:00:00
> [04/03 10:26:49] d2.evaluation.evaluator INFO: Total inference time: 0:00:21.067479 (0.042561 s / img per device, on 4 devices)
> [04/03 10:26:49] d2.evaluation.evaluator INFO: **Total inference pure compute time: 0:00:12 (0.025790 s / img per device, on 4 devices)**
> [04/03 10:26:49] d2.evaluation.panoptic_evaluation INFO: Writing all panoptic predictions to output/yoso_resnet50_panoptic_seg_ade20k/inference ...
> [04/03 10:26:58] d2.evaluation.panoptic_evaluation INFO: Panoptic Evaluation Results:

> |        |   PQ   |   SQ   |   RQ   |  #categories  |
> |:------:|:------:|:------:|:------:|:-------------:|
> |  All   | 38.038 | 79.400 | 45.979 |      150      |
> | Things | 37.334 | 80.405 | 45.643 |      100      |
> | Stuff  | 39.446 | 77.390 | 46.651 |      50       |

> [04/03 10:26:58] d2.engine.defaults INFO: Evaluation results for ade20k_panoptic_val in csv format:
> [04/03 10:26:58] d2.evaluation.testing INFO: copypaste: Task: panoptic_seg
> [04/03 10:26:58] d2.evaluation.testing INFO: copypaste: PQ,SQ,RQ,PQ_th,SQ_th,RQ_th,PQ_st,SQ_st,RQ_st
> [04/03 10:26:58] d2.evaluation.testing INFO: copypaste: 38.0377,79.4002,45.9790,37.3336,80.4054,45.6428,39.4459,77.3897,46.6512
